### ISSUE TITLE
入會程序與章程頁面搬遷

### ISSUE THREAD

**Issue by bestian** [3dw/members-frontend#37]
入會程序與章程頁面搬遷

**Comment by leechiuhui** [comment]
<img width="318" alt="截圖 2024-12-10 晚上10 22 47" src="https://github.com/user-attachments/assets/c6c17cf9-ccad-45af-a071-6af75466e8df">
<img width="308" alt="截圖 2024-12-10 晚上10 34 10" src="https://github.com/user-attachments/assets/9660e45e-53a7-4daa-a486-7da4d4a86f4a">
<img width="302" alt="截圖 2024-12-10 晚上10 42 46" src="https://github.com/user-attachments/assets/f247a617-ce4d-4a57-9b74-9346a856c259">
