### ISSUE TITLE
側邊選項和上方欄位重複

### ISSUE THREAD

**Issue by jungleft** [3dw/members-frontend#58]
側邊選項和上方欄位有重複的資訊，是否選一邊放就好，或是上方欄位簡化為圖示呢？

![未命名](https://github.com/user-attachments/assets/7e079b43-9d29-4899-8502-4d35a33f2a4f)
<img width="474" alt="未命名2" src="https://github.com/user-attachments/assets/35ffa8db-4860-444c-8115-30d740d32886" />

**Comment by bestian** [comment]
@jungleft 目前重覆是沒有關係。
放在頂欄的是要"比較突顯"的項目, 側欄則是"所有項目"
